/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Zeo
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ViewAgenda1
     */
    public ViewPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        Jb_nuevo = new javax.swing.JButton();
        Jb_modificar = new javax.swing.JButton();
        Jb_insertar = new javax.swing.JButton();
        Jb_eliminar = new javax.swing.JButton();
        Jl_idioma = new javax.swing.JLabel();
        Jtf_nombre = new javax.swing.JTextField();
        Jtf_idioma = new javax.swing.JTextField();
        Jl_nombre = new javax.swing.JLabel();
        Jl_genero = new javax.swing.JLabel();
        Jl_duracion = new javax.swing.JLabel();
        Jl_clasificacion = new javax.swing.JLabel();
        Jtf_duracion = new javax.swing.JTextField();
        Jtf_clasificacion = new javax.swing.JTextField();
        Jtf_genero = new javax.swing.JTextField();
        Jtf_id_peliculas = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));

        jbtn_primero.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jbtn_primero.setText("|<");

        jbtn_anterior.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jbtn_anterior.setText("<<");

        jbtn_siguiente.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jbtn_siguiente.setText(">>");

        jbtn_ultimo.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jbtn_ultimo.setText(">|");

        Jb_nuevo.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_nuevo.setText("Nuevo");

        Jb_modificar.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_modificar.setText("Modificar");

        Jb_insertar.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_insertar.setText("Insertar");

        Jb_eliminar.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_eliminar.setText("Eliminar");

        Jl_idioma.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_idioma.setText("Idioma");

        Jl_nombre.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_nombre.setText("Nombre");

        Jl_genero.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_genero.setText("Genero");

        Jl_duracion.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_duracion.setText("Duracion");

        Jl_clasificacion.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_clasificacion.setText("Clasificacion");

        Jtf_clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_clasificacionActionPerformed(evt);
            }
        });

        Jtf_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_generoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jl_clasificacion)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Jl_genero)
                            .addGap(58, 58, 58)
                            .addComponent(Jtf_genero))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jl_nombre)
                                .addComponent(Jl_idioma))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Jtf_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Jtf_id_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Jl_duracion)
                            .addGap(43, 43, 43)
                            .addComponent(Jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jb_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_ultimo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jb_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_eliminar)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(Jtf_id_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_nombre)
                    .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_idioma)
                    .addComponent(Jtf_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_genero)
                    .addComponent(Jtf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_duracion)
                    .addComponent(Jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_clasificacion)
                    .addComponent(Jtf_clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_anterior)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_ultimo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_nuevo)
                    .addComponent(Jb_modificar)
                    .addComponent(Jb_insertar)
                    .addComponent(Jb_eliminar))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_clasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_clasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_clasificacionActionPerformed

    private void Jtf_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_generoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jb_eliminar;
    public javax.swing.JButton Jb_insertar;
    public javax.swing.JButton Jb_modificar;
    public javax.swing.JButton Jb_nuevo;
    public javax.swing.JLabel Jl_clasificacion;
    public javax.swing.JLabel Jl_duracion;
    public javax.swing.JLabel Jl_genero;
    public javax.swing.JLabel Jl_idioma;
    public javax.swing.JLabel Jl_nombre;
    public javax.swing.JTextField Jtf_clasificacion;
    public javax.swing.JTextField Jtf_duracion;
    public javax.swing.JTextField Jtf_genero;
    public javax.swing.JTextField Jtf_id_peliculas;
    public javax.swing.JTextField Jtf_idioma;
    public javax.swing.JTextField Jtf_nombre;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    // End of variables declaration//GEN-END:variables
}
